# define inputs

In [42]:
import matplotlib.pyplot as plt
import numpy as np
Return = 0.07
years = 25
starting_tfsa = 5000
starting_rrsp = 10000
starting_general = 5000

In [8]:
def calculate(MER, AMF, balance, Trading_fee, Return):
    new = balance*(1 + Return - MER) - AMF - Trading_fee
    tot_MER = (balance*(1 + Return) - new)/balance
    Tot_return = new/balance
    return new, tot_MER, Tot_return;

In [14]:
x = calculate(0.0064, 100, 5000, 50, Return)
print(x)

(5168.000000000001, 0.03639999999999982, 1.0336)


In [49]:
values = np.zeros( (years,3) )
values[0] = calculate(0.0064, 100, 5000, 50, Return)
for year in range(years):
    if year >0:
        values[year] = calculate(0.0064, 100, values[year-1,0], 50, Return)
    
    
    
    

In [37]:
print(values)

[[  5.16800000e+03   3.64000000e-02   1.03360000e+00]
 [  5.34668480e+03   3.54247678e-02   1.03457523e+00]
 [  5.53673395e+03   3.44547677e-02   1.03554523e+00]
 [  5.73887023e+03   3.34917839e-02   1.03650822e+00]
 [  5.95386238e+03   3.25375487e-02   1.03746245e+00]
 [  6.18252803e+03   3.15937298e-02   1.03840627e+00]
 [  6.42573681e+03   3.06619199e-02   1.03933808e+00]
 [  6.68441367e+03   2.97436265e-02   1.04025637e+00]
 [  6.95954238e+03   2.88402629e-02   1.04115974e+00]
 [  7.25216928e+03   2.79531413e-02   1.04204686e+00]
 [  7.56340724e+03   2.70834665e-02   1.04291653e+00]
 [  7.89443994e+03   2.62323315e-02   1.04376767e+00]
 [  8.24652632e+03   2.54007146e-02   1.04459929e+00]
 [  8.62100540e+03   2.45894769e-02   1.04541052e+00]
 [  9.01930134e+03   2.37993627e-02   1.04620064e+00]
 [  9.44292890e+03   2.30309999e-02   1.04696900e+00]
 [  9.89349918e+03   2.22849020e-02   1.04771510e+00]
 [  1.03727257e+04   2.15614709e-02   1.04843853e+00]
 [  1.08824311e+04   2.08610

In [53]:
print(values[:,2])

[ 1.0336      1.03457523  1.03554523  1.03650822  1.03746245  1.03840627
  1.03933808  1.04025637  1.04115974  1.04204686  1.04291653  1.04376767
  1.04459929  1.04541052  1.04620064  1.046969    1.0477151   1.04843853
  1.049139    1.04981632  1.05047038  1.0511012   1.05170886  1.0522935
  1.05285538]


In [52]:
year=np.year[1,0:year,year+1];

AttributeError: module 'numpy' has no attribute 'year'

In [43]:
plt.gca().set_color_cycle(['red', 'green', 'blue', 'yellow'])

/Users/winstonfortowsky/anaconda3/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:106: MatplotlibDeprecationWarning: The set_color_cycle attribute was deprecated in version 1.5. Use set_prop_cycle instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)


In [54]:
plt.plot(values[:,1], values[:,2])